apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-nexus 
spec:
  ingressClassName: nginx
  rules:
  - host: api-nexus.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: api-nexus
            port:
              number: 80

